### ISSUE TITLE
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml

### ISSUE THREAD

**Issue by Arcelibs** [sky0966548546/MangaDownload#1]
是不是要多加一個 pip install lxml ?

**Comment by sky9154** [comment]
是的，或是將
https://github.com/sky9154/MangaDownload/blob/866d8cfbd224507ecc3b5cd03ff7b6dc395283ce/manga.py#L53
改為 Python 內建的 html.parser 
```python
html = bs(result, "html.parser")
```
如果要解析速度快一點的還是用 lxml 比較好
