### ISSUE TITLE
the requested URL 'http://localhost:8763/index.html' caused an error:

### ISSUE THREAD

**Issue by RonaldYuren** [sky0966548546/MangaDownload#2]
你好，
我後來使用發現了如題目提到的error 404
我目前是使用windows 的cmd   跑python3 launcher.py

**Comment by sky9154** [comment]
如果是用cmd執行要先將cmd的位置變更為檔案所在的位置，在進行操作。
用法1: 
```cmd
cd 目錄
```

範例:
![](https://cdn.discordapp.com/attachments/900320455477579836/991144329626255420/unknown.png)

用法2:
資料夾內右鍵，選擇 `在終端中開啟`，再進行操作。

![](https://cdn.discordapp.com/attachments/900320455477579836/991144566239526932/unknown.png)
